name: Publish Pacts to PactFlow

on:
  push:
    branches:
      - main

jobs:
  publish-pacts:
    runs-on: ubuntu-latest

    env:
      PACT_BROKER_URL: https://hmcts-dts.pactflow.io
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      PACT_ENV: dev/pactTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permissions for scripts
        run: chmod +x ./publish-pacts.sh

      - name: Run pact publish script
        run: ./publish-pacts.sh
